### ISSUE TITLE
SSL connection example

### ISSUE THREAD

**Issue by dfox-loc** [marklogic/flux#245]
Would you be able to add an example of connecting to an app server with SSL enabled? With MLCP and Corb this is as easy as supplying the -ssl param, but it seems that Flux expects something else. Any pointers would be appreciated!

**Comment by rjrudin** [comment]
Thanks @dfox-loc  for the note - you're right, we need a concrete example. You'll start with `--ssl-protocol`, which is telling Flux to create an SSL connection. The `--truststore-` options then let you configure 1-way SSL so that Flux knows whether to trust the server certificate or not. The `--keystore-` options let you configure 2-way SSL, so you can tell Flux which Java keystore to use for presenting a certificate to the server. 

As noted in https://marklogic.github.io/flux/common-options.html#connecting-to-marklogic , if you configure any of the `--keystore-` or `--truststore-` options, then `--ssl-protocol` will default to "TLSv1.2", so you won't need to specify that unless you need some new values. 

But concrete examples will be better. We'll get those added very soon.

**Comment by dfox-loc** [comment]
I was able to get this working, but I actually had to provide --ssl-protocol "TLSv1.2", despite having all of the --truststore-* params. without providing the ssl version I was getting 403 errors on the flux side, and on the MarkLogic side I was seeing TLS errors. so there might be an issue with the default? if it helps here is my working command:

`flux export-files \
--path "data/" \
--collections "test" \
--host "hostname" \
--port "8002" \
--connection-type "DIRECT" \
--user "user" \
--password "pass" \
--database "Documents" \
--ssl-hostname-verifier "ANY" \
--ssl-protocol "TLSv1.2" \
--truststore-path "/workspaces/flux-demo/truststore.jks" \
--truststore-password "pass" \
--truststore-type "JKS" \
--stacktrace`

if i remove just the ssl-protocol param it stops working.

**Comment by rjrudin** [comment]
Your findings are correct and we need to correct the docs - `--ssl-protocol` has a default value if a keystore is specified, but not if only a truststore is specified. There's a reason for this - it involves support for certificate-based authentication - but the docs need to state the correct thing. 

We'll have the docs fixed and will have examples of 1-way and 2-way SSL tomorrow (2024-09-11), along with common SSL errors and what the typical fix is. Thanks again for your report!

**Comment by rjrudin** [comment]
@dfox-loc Please see the [new sections in the user guide](https://marklogic.github.io/flux/common-options.html) on configuring one-way and two-way SSL and debugging some common errors.
